<?php
/**
 * ProjectName: PowerPterodactylAPI.
 * Author: SaigyoujiYuyuko
 * QQ: 3558168775
 * Date: 2019/3/2
 * Time: 13:25
 *
 * Copyright © 2019 SaigyoujiYuyuko. All rights reserved.
 */

namespace Exception;

use \Exception;
use Throwable;

class ArgumentNotValid extends Exception {

    public function __construct(string $message = "", int $code = 1, Throwable $previous = null){
        parent::__construct($message, $code, $previous);
    }

    public function __toString(){
        parent::__toString(); // TODO: Change the autogenerated stub

        return "The Argument[".$this->getMessage()."] is not valid! In file:".$this->getFile()." on line ".$this->getLine()." Error trace: ".$this->getTraceAsString();
    }

}